language: ruby
rvm:
  - 2.5.3
services:
  - postgresql
  - elasticsearch
before_script:
  - bundle exec rake db:create --all
  - bundle exec rake db:migrate
script:
  - bundle exec rake ci:tests
notifications:
  email: false