language: ruby
rvm:
  - 2.5.3
addons:
  postgresql: 10
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database nekonata_test;' -U postgres
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec